<a href="https://colab.research.google.com/github/Imran-Rahman-Rifat/Pytorch-Practise/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np



In [2]:
##list
my_list =[[1, 2, 3], [4, 5, 6]]
my_list

[[1, 2, 3], [4, 5, 6]]

In [3]:
#numpy
np1 = np.random.rand(3, 4)
np1

array([[0.43641125, 0.2698048 , 0.90664448, 0.63827707],
       [0.29105705, 0.29579774, 0.43848536, 0.98643587],
       [0.67441881, 0.58232359, 0.27846953, 0.56160514]])

In [6]:
#tensor
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.0425, 0.7101, 0.8371, 0.6556],
        [0.2816, 0.9253, 0.5485, 0.6716],
        [0.8217, 0.6326, 0.6190, 0.1192]])

In [7]:
tensor_x = torch.tensor(np1)
tensor_x

tensor([[0.4364, 0.2698, 0.9066, 0.6383],
        [0.2911, 0.2958, 0.4385, 0.9864],
        [0.6744, 0.5823, 0.2785, 0.5616]], dtype=torch.float64)